### ISSUE TITLE
support for single push button

### ISSUE THREAD

**Issue by adidoes** [duhow/hass-cover-time-based#2]
hello,

does this support having one single button for up, down and stop? i tried putting the same entity in both fields during setup but the button states are not displayed correctly in the dashboard (all 3 up down and stop buttons are clickable all the time and the stop button doesn't work).

**Comment by klim123123** [comment]
same problem here, please make possible at least trigger a script, where we can put any buttons and would be nice to trigger services too.
e.g.
```
open_cover:
  service: cover.open_cover
    target:
      entity_id: cover.shtora_spalnia
close_cover:
  service: cover.close_cover
    target:
      entity_id: cover.shtora_spalnia
```
or at least
```
close_switch_entity_id: script.cover_spalny_close
open_switch_entity_id: script.cover_spalny_open
```
